name: SonarQube analysis

on:
  push: # Run on every push to any branch
    branches: ["*"]
  pull_request: # Run on every pull request to any branch
    branches: ["*"]
  workflow_dispatch: # Allow manual triggering of the workflow

permissions:
  pull-requests: read # Allows SonarQube to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # SonarQube token
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}   # SonarQube host URL
        with:
          args: >
            -Dsonar.projectKey=["IMS"]
