name: SonarCloud Analysis and Deployment

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    name: Build, Analyze, and Deploy
    runs-on: windows-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # SonarQube token
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}   # SonarQube host URL
        with:
          args: >
            -Dsonar.projectKey=IMS
