name: SonarQube analysis

on:
  push: # Run on every push to any branch
    branches: ["*"]
  pull_request: # Run on every pull request to any branch
    branches: ["*"]
  workflow_dispatch: # Allow manual triggering of the workflow

permissions:
  pull-requests: read # Allows SonarQube to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          
      - name: Download and install SonarScanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-windows.zip
          tar -xvf sonar-scanner.zip
          echo "SONAR_SCANNER_HOME=$(pwd)/sonar-scanner-4.7.0.2747-windows" >> $GITHUB_ENV
          echo "$(pwd)/sonar-scanner-4.7.0.2747-windows/bin" >> $GITHUB_PATH

      - name: Run SonarQube Scanner
        run: |
          sonar-scanner \
            -Dsonar.projectKey=IMS \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # SonarQube token
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}   # SonarQube host URL
